# Generated by Django 3.0.5 on 2020-06-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='git',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='utube',
            field=models.URLField(blank=True),
        ),
    ]
